"""add file_hash to syllabi

Revision ID: 0533e80abc21
Revises: 11ab70ebb241
Create Date: 2026-02-23 13:55:45.289405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0533e80abc21'
down_revision = '11ab70ebb241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syllabi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_syllabi_file_hash'), ['file_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('syllabi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_syllabi_file_hash'))
        batch_op.drop_column('file_hash')

    # ### end Alembic commands ###
